project:
  output-dir: _output

toc: true
#number-sections: true
#bibliography: references.bib
from: markdown+emoji
date: today
date-format: "MMMM YYYY"

execute:
  freeze: auto

format:
  revealjs:
    theme: [night, custom.scss]
    embed-resources: true
    margin: 0.15
    stretch: false
    centre: true
    toc-depth: 2
    center-title-slide: true
    center: false
    logo: ./media/logo-gedem_white.png
    footer: a short guide for better data management. If you liked it, find more [here](https://a_link_to_the_website)
    transition: slide
    background-transition: fade
    navigation-mode: vertical
    controls-layout: bottom-right
    controls-tutorial: true
    overview: true
    css: logo.css

    title-slide-attributes:
      data-background-image: ./media/logo-gedem_white.png
      data-background-size: contain
      data-background-opacity: "0.2"